### ISSUE TITLE
Angularjs $resource

### ISSUE THREAD

**Issue by 0xNacho** [lirantal/operations-orchestration-backup#1]
Why not use $resource instead of $http?

$resource is a factory which creates a resource object that lets you interact with RESTful server-side data sources.

Some interesting links:
- http://www.sitepoint.com/creating-crud-app-minutes-angulars-resource/
- https://docs.angularjs.org/api/ngResource/service/$resource
- http://stackoverflow.com/questions/13181406/angularjs-http-and-resource

**Comment by lirantal** [comment]
where do you see the use of $resource in the code?

**Comment by 0xNacho** [comment]
sorry,can you close this? I was wrong (wrong place :) )

**Comment by lirantal** [comment]
It's ok, of course :)
